# use vim as the visual editor
export VISUAL=vim
export EDITOR=$VISUAL

# ensure dotfiles bin directory is loaded
export PATH="/usr/local/bin:/usr/local/sbin:$PATH"
export PATH="/usr/local/opt/elasticsearch@2.4/bin:$PATH"
export PATH="$HOME/.bin:$PATH"
export PATH="$HOME/.npm/bin:$PATH"
export PATH="$(npm bin):$PATH"
export PATH="$HOME/.cargo/bin"
export PATH="/Applications/Postgres.app/Contents/Versions/latest/bin:$PATH"
export PATH="/Applications/MiniZincIDE.app/Contents/Resources/:$PATH"

export DYLD_LIBRARY_PATH="$(rustc --print sysroot)/lib:$DYLD_LIBRARY_PATH"

# Local config
[[ -f ~/.zshenv.local ]] && source ~/.zshenv.local
